export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const NEW_TRACKER = 'NEW_TRACKER';
export const SET_TRACKER = 'SET_TRACKER';
export const ADD_TRACKER = 'ADD_TRACKER';
export const UPDATE_TRACKER = 'UPDATE_TRACKER';
export const REMOVE_TRACKER = 'REMOVE_TRACKER';
export const FETCH_TRACKERS = 'FETCH_TRACKERS';
